<a href="https://colab.research.google.com/github/agnesjoethomas/numpy-learning/blob/main/nov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# wap to find the length of each word in a given list
l=["apple","orange","mango"]
nl=[]
for i in l:
  nl.append(len(i))
print(nl)

[5, 6, 5]


In [ ]:
import numpy as np


In [ ]:
l=[1,2,3,4]
z=np.array(l)

print(z) # no comma in btwn

[1 2 3 4]


In [ ]:
l=[1,2.0,3,4]
z=np.array(l)
z # system convert to same data type and makes array of same data type

array([1., 2., 3., 4.])

In [ ]:
l=[1,2,3,"4"]
z=np.array(l)
z # possible

array(['1', '2', '3', '4'], dtype='<U21')

In [ ]:
l=[1,2,3,4,5]
z=np.array(l)
print(z)

[1 2 3 4 5]


In [ ]:
z[-1]



np.int64(5)

In [ ]:
z[2:]

array([3, 4, 5])

In [ ]:
z[-2]

np.int64(4)

In [ ]:
z[-3:]

array([3, 4, 5])

In [ ]:
z[-1:-4:-1]

array([5, 4, 3])

In [ ]:
z[::-1]

array([5, 4, 3, 2, 1])

**operations on array**

In [ ]:
z.ndim

1

In [ ]:
z.size

5

In [ ]:
np.size(z)

5

In [ ]:
z.shape # gives dimensions as in no of rows and columns

(5,)

In [ ]:
z=np.array([[1,2],[4,5]])
print(z)

[[1 2]
 [4 5]]


In [ ]:
print(z.size)
print(z.ndim)
print(z.shape)

4
2
(2, 2)


In [ ]:
z=np.array([[[1,2],[3,4]],[[3,4],[4,5]]])
print(z)
print(z.shape) # 2 row,2 coloumn, 2 matrix
print(z.ndim)
print(z.size)

[[[1 2]
  [3 4]]

 [[3 4]
  [4 5]]]
(2, 2, 2)
3
8


In [ ]:
#a 2x3 matrix
z=np.array([[1,2,3],[4,5,6]])
print(z)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 4x2
z=np.array([[1,2],[3,4],[5,6],[7,8]])
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# 4x4
z=np.array([[1,2,3,4],[1,21,31,41],[1,22,31,42],[1,21,23,42]])
print(z)

[[ 1  2  3  4]
 [ 1 21 31 41]
 [ 1 22 31 42]
 [ 1 21 23 42]]


In [ ]:
z[2,2] # 3rd row 3rd col elmt

np.int64(31)

In [ ]:
z[3,3] #  4th row 4th col element

np.int64(42)

In [ ]:
z[3,1:3] # 4th row which all columns

array([21, 23])

In [ ]:
z[1:3,1:3] # second row,3rd row, 2nd 3rd cols

array([[21, 31],
       [22, 31]])

In [ ]:
z[0:3,1:3]

array([[ 2,  3],
       [21, 31],
       [22, 31]])

In [ ]:
print(z[1:,1:])

[[21 31 41]
 [22 31 42]
 [21 23 42]]


In [ ]:
# zero matrix
z=np.zeros([2,2],dtype=int) #dtype is float by default
z

array([[0, 0],
       [0, 0]])

In [ ]:
z=np.zeros([2,2],dtype=complex)
z

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [ ]:
z=np.zeros([2,2,2],dtype=int)# tensor
z

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [ ]:
# one matrix
z=np.ones([3,3],dtype=int) # dtype=complex or whatever
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# create a 2x2 matrix
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
b=np.array([[5,6],[7,6]])
print(b)

[[5 6]
 [7 6]]


In [ ]:
a+b

array([[ 6,  8],
       [10, 10]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -2]])

In [ ]:
a/b # elementary division

array([[0.2       , 0.33333333],
       [0.42857143, 0.66666667]])

In [ ]:
a*b # elementary multiplication

array([[ 5, 12],
       [21, 24]])

In [ ]:
a@b # mat mul

array([[19, 18],
       [43, 42]])

In [ ]:
a.dot(b) #matmul

array([[19, 18],
       [43, 42]])

In [ ]:
z=np.matmul(a,b)
z

array([[19, 18],
       [43, 42]])

In [ ]:
# full matrix
z=np.full([2,2],2)
print(z)

[[2 2]
 [2 2]]


In [ ]:
import numpy as np

In [ ]:
a=np.eye(3) #dtype=int or...... np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create a 3x3 identity matrix
iden=np.identity(3)
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a)
print(iden)
print(a.shape)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


Reshaping matrix with same no of elements

In [ ]:
z=a.reshape(1,9)
print(z)

[[1 2 3 3 4 5 5 6 7]]


In [ ]:
z=a.reshape(9,1)
print(z)

[[1]
 [2]
 [3]
 [3]
 [4]
 [5]
 [5]
 [6]
 [7]]


In [ ]:
# list(range(1,10))
#[1,2,3,4,5,6,7,8,9]

b=np.arange(1,10,2) # same as range but converted to array
print(b)

[1 3 5 7 9]


In [ ]:
# create a 5x2 matrix without using np.array

b=np.arange(1,11).reshape(5,2)
print(b)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
